### ISSUE TITLE
Close icons color

### ISSUE THREAD

**Issue by Sroka** [Vincent-P/gruvbox-intellij-theme#1]
Hey, awesome that someone finally ported gruvbox to Intellij theme, thank you. Hope you win some in Intellij theme contest :) 

Could you change close icons color to be a bit brighter? They are nearly invisible currently:
![image](https://user-images.githubusercontent.com/2983710/57061427-1052ee80-6cbd-11e9-8903-f900bff01ddc.png)

**Comment by Vincent-P** [comment]
Thank you for the report!
I will try to fix it today :)

**Comment by Vincent-P** [comment]
I have uploaded the new version to the jetbrains repository.
It usually takes 2 business days for them to process the update.
