### ISSUE TITLE
Doc comments in C/C++

### ISSUE THREAD

**Issue by Rexagon** [Vincent-P/gruvbox-intellij-theme#10]
There are doc comment style settings in **Color Scheme > Language Defaults > Comments** and it looks great in preview window. However **C/C++** color scheme tab doesn't have any inherited doc comment styles so block comments with doxygen looks plain and hard to read.

Is it possible to add doc comments highlighting (tags, values, etc) in C/C++?

I'm using CLion 2019.2.1

**Comment by Vincent-P** [comment]
Sorry for the late answer, can you add a screenshot?
