### ISSUE TITLE
[Feature request] Add light version of Gruvbox

### ISSUE THREAD

**Issue by ghost** [Vincent-P/gruvbox-intellij-theme#11]
Could you add light version of gruvbox color theme to the plugin?

**Comment by Vincent-P** [comment]
Not planned at the moment.
If someone wants to try to do it I gladly accept PRs.

**Comment by mariushelf** [comment]
I have created a basic light version here: https://github.com/mariushelf/gruvbox-intellij-theme/tree/light-version
I have simply searched for usages of "dark" colors as defined in the original vim schema, and replaced them with the respective light versions.
There are a few colors used that are not defined in the original vim schema. I am not sure on how choose good light colors. Any input is very much appreciated.
Also if @Vincent-P would like to adopt my branch I'm very much open for it.

**Comment by mariushelf** [comment]
After some more tinkering, it seems that the only unmapped color is now f8e1aa, e.g. for brackets and the selected indentation line. Lacking a better option I've just removed that color. PR coming your way soon :)

**Comment by mariushelf** [comment]
https://github.com/Vincent-P/gruvbox-intellij-theme/pull/26

**Comment by Vincent-P** [comment]
I merged the PR and fixed a few colors, light versions are on master!
I'll publish an update once other issues are fixed.
