### ISSUE TITLE
[Bug] Diagram turn white in latest version of IDEA

### ISSUE THREAD

**Issue by lixin-wei** [Vincent-P/gruvbox-intellij-theme#12]
Hi, I love your theme very much but I find an issue that is very annoying.

![image](https://user-images.githubusercontent.com/19600697/67542753-d0773c00-f720-11e9-8830-fdba45520f1b.png)

As picture shows, diagram turned to white in your theme, which is quite  unreadable. Could you please fix it?

IntelliJ IDEA 2019.2.3 (Ultimate Edition)
macOS 10.15

**Comment by lixin-wei** [comment]
FYI, only non-project class will be white, QueueOperationResult is a class in my project and his color is ok.
![image](https://user-images.githubusercontent.com/19600697/67542901-86428a80-f721-11e9-9124-6bac226ed352.png)

**Comment by Vincent-P** [comment]
I will look into it tonight.

**Comment by lixin-wei** [comment]
Hello, how are things going?

**Comment by Vincent-P** [comment]
I can't reproduce it, can you share a small project showcasing your problem?

**Comment by lixin-wei** [comment]
[helloworld.zip](https://github.com/Vincent-P/gruvbox-intellij-theme/files/3801789/helloworld.zip)

You can use this project. Just open Main.java and place cursor to line 5's `ThreadPoolExecutor`, then press cmd+option+U, or right click -> Diagrams -> Show Diagram Popup.

![image](https://user-images.githubusercontent.com/19600697/68088557-5de22b00-fe9b-11e9-8599-fc77cfc4a845.png)

And the detailed version info here, FYI:

IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Subscription is active until January 1, 2020
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: GrepConsole, Lombook Plugin, com.jetbrains.lightThemePreview, com.vincentp.gruvbox-theme, Pythonid

**Comment by lixin-wei** [comment]
And the version of your theme is 0.2.1

![image](https://user-images.githubusercontent.com/19600697/68088675-4f484380-fe9c-11e9-9516-fa088ad90c78.png)

**Comment by Vincent-P** [comment]
The problem might be related to your configuration, I don't have the same colors as you in the diagram.
![image](https://user-images.githubusercontent.com/10779205/68154878-c804d980-ff48-11e9-83f8-0fa48370265f.png)

EDIT: Have you changed the File Colors in the Settings?
![image](https://user-images.githubusercontent.com/10779205/68155068-419cc780-ff49-11e9-877c-b0e9f6a7f422.png)

**Comment by lixin-wei** [comment]
It's weird... my File Colors in the Settings is the same as yours.
And I disabled all other plugins, problem still exists...

EDIT: I remove preferences and caches of IDEA to reset it's settings, but problem still exists.

Could your please provide your settings file so I can reset settings to yours?

By the way, here is my settings file, could your reproduce with this settings?
[settings.zip](https://github.com/Vincent-P/gruvbox-intellij-theme/files/3807111/settings.zip)

**Comment by Vincent-P** [comment]
I can't reproduce even with your settings, and my settings were the default ones as I don't use IDEA myself.
Have you tried to reset your config and just installing the gruvbox-theme?

**Comment by cuifuan** [comment]
> 即使使用您的设置，我也无法重现。由于我自己不使用IDEA，因此我的设置是默认设置。
> 您是否尝试过重置配置并仅安装gruvbox-theme？

idea version 2019.2.4
![image](https://user-images.githubusercontent.com/23448967/68914941-33497980-079b-11ea-8381-0faa29575d47.png)

System: Mac OS_X 10.15

**Comment by cuifuan** [comment]
hello,Have you solved it?

**Comment by cuifuan** [comment]
![image](https://user-images.githubusercontent.com/23448967/68916047-59711880-079f-11ea-9b16-7225799e5005.png)
Color set to black
![image](https://user-images.githubusercontent.com/23448967/68916086-7dccf500-079f-11ea-9d6b-288747c99ce6.png)
Can be closed

**Comment by Vincent-P** [comment]
Maybe something is wrong with the file colors then. I don't see the "brown" key in the json file so maybe it's because of that.
I will try to fix it tonight!

**Comment by Vincent-P** [comment]
Okay so I don't see where the Brown color is defined...
You can set the custom color to #5C4D2A and it should work.
