### ISSUE TITLE
when i switch to light theme, the background color of 'target' dir is still black

### ISSUE THREAD

**Issue by xiaohundun** [Vincent-P/gruvbox-intellij-theme#14]
~~light theme~~ = other theme

![image](https://user-images.githubusercontent.com/38812912/72123130-46438900-339b-11ea-8c7c-95a97a9e3394.png)

**Comment by xiaohundun** [comment]
![image](https://user-images.githubusercontent.com/38812912/72131186-7fd5bd80-33b6-11ea-88ce-0d41cec89fe6.png)

**Comment by xiaohundun** [comment]
![image](https://user-images.githubusercontent.com/38812912/72132730-a72e8980-33ba-11ea-8b38-ba6555e731d0.png)

**Comment by rgomezcasas** [comment]
Hey, is this happening even if you restart the IntelliJ?

**Comment by Vincent-P** [comment]
I am not sure if it's related to gruvbox
