### ISSUE TITLE
Possible to make a contrast version?

### ISSUE THREAD

**Issue by rafmst** [Vincent-P/gruvbox-intellij-theme#15]
Do you think its possible to make a contrast version where the sidebar is a shade darker then de code, just to make a clear separation to the eye?

This would be very apreciated by me :)

**Comment by Vincent-P** [comment]
I just added the Dark Soft and Dark Hard variants.
With these, you can select the Hard UI theme with the Medium color scheme so that the UI is slightly darker than the code.
Let me know what you think when the plugin review is done!

**Comment by rafmst** [comment]
How could I test it?

**Comment by Vincent-P** [comment]
The theme was updated last week.
