### ISSUE TITLE
Latest Gruvbox Theme 0.2.1 is incompatible with  IDEA 2020.1 

### ISSUE THREAD

**Issue by larrynikx** [Vincent-P/gruvbox-intellij-theme#19]
**Short Description**
IDEA plugin is incompatible therefore the theme can not be applied.

**Steps to Reproduce**
Update IDEA to 2020.1

**Comment by Vincent-P** [comment]
Duplicate of #16

**Comment by stephanoparaskeva** [comment]
This was closed as a duplicate of #16 but #16 was also closed referencing this. Does that mean the issue was resolved?
