### ISSUE TITLE
Different color for files inside the project section

### ISSUE THREAD

**Issue by rgomezcasas** [Vincent-P/gruvbox-intellij-theme#2]
Hey! First of all thanks for the theme, it's awesome! 👏 

I noticed that when you have the focus in the editor or in the "project", the selected file background color is the same:

![gruvbox_theme theme json  gruvbox-intelli… 2019-05-07 11-30-55](https://user-images.githubusercontent.com/1331435/57289409-9905cc00-70bb-11e9-9f35-3cf095c1967b.png)

But in the default themes it's different (and I think we're used to it :)

Focus in the "project":
![gruvbox_theme theme json  gruvbox-intelli… 2019-05-07 11-29-43](https://user-images.githubusercontent.com/1331435/57289318-6cea4b00-70bb-11e9-9705-313be1deada9.png)

 
Focus in the editor:
![gruvbox_theme theme json  gruvbox-intelli… 2019-05-07 11-29-56](https://user-images.githubusercontent.com/1331435/57289331-75428600-70bb-11e9-8a85-17fc4c0c626a.png)

Would you like to have different colors for it? 😊

Thanks!

**Comment by Vincent-P** [comment]
Hi! Thanks a lot for your post.
I indeed did not think of that, if you have any suggestions feel free to tell me or make a PR :)
If not then I will see if I can come up with a nice color for the unfocused current file.

**Comment by rgomezcasas** [comment]
Maybe we could try with a `665c54` color
![gruvbox: Retro groove color scheme for Vim 2019-05-07 15-08-07](https://user-images.githubusercontent.com/1331435/57301714-f14bc680-70d9-11e9-9945-ad5aad41b8df.png) 🤔

**Comment by rgomezcasas** [comment]
In some hours I'll do a pr with this! :)
