### ISSUE TITLE
With "Gruvbox Dark Hard" I can't see selected Tool Window header 

### ISSUE THREAD

**Issue by illetschko** [Vincent-P/gruvbox-intellij-theme#21]
In gruvbox_dark_hard.theme.json there are the same values under "colors" for "bg" and "bg0_h".

So a selected Tool Window has the same "Header" as an unselected.

My workaround was setting "bg0_h": "#000000"
Now the selected header is black.
But I don't know if this is the best way to solve this....

**Comment by Vincent-P** [comment]
It should be fixed with latest update can you confirm?

**Comment by illetschko** [comment]
Oh, Yes.
It looks very good now.
