### ISSUE TITLE
Support 2020.1 (PyCharm)

### ISSUE THREAD

**Issue by Elijas** [Vincent-P/gruvbox-intellij-theme#22]
```(until build 195.SNAPSHOT < PC-201.6668.115).```

![image](https://user-images.githubusercontent.com/4084885/79565844-2a4a3480-80ba-11ea-98be-47a9fb9812e1.png)

```
PyCharm 2020.1 (Community Edition)
Build #PC-201.6668.115, built on April 7, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-46-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1923M
Current Desktop: ubuntu:GNOME
```

**Comment by Vincent-P** [comment]
Is it still not working? Latest version is 0.3.0 not 0.2.1.

**Comment by Elijas** [comment]
Now it works, thank you!
![image](https://user-images.githubusercontent.com/4084885/79874824-7ca88f80-83f1-11ea-8065-f51827eadcd3.png)
![image](https://user-images.githubusercontent.com/4084885/79874827-7dd9bc80-83f1-11ea-8239-73293db85b1a.png)
