### ISSUE TITLE
Support Android Studio 3.6.2

### ISSUE THREAD

**Issue by blfpd** [Vincent-P/gruvbox-intellij-theme#23]
![Screenshot from 2020-04-17 17-58-19](https://user-images.githubusercontent.com/2727048/79589080-1e1fa080-80d5-11ea-982b-4c227fe4190b.png)

```
Android Studio 3.6.2
Build #AI-192.7142.36.36.6308749, built on March 18, 2020
Runtime version: 1.8.0_212-release-1586-b4-5784211 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.3-300.fc32.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: 
```

**Comment by Vincent-P** [comment]
I will take a look at it tomorrow :)

**Comment by blfpd** [comment]
Merci ! But there is no urge :blush:

**Comment by Vincent-P** [comment]
It seems to work on Android Studio 3.6.3.
Have you tried to install the theme using the Marketplace? It looks like you tried to install the theme by importing it as a Color Scheme.
If you want to install it manually, you have to import the file in the Plugins page instead.

**Comment by blfpd** [comment]
You’re right! I was new to Android Studio and didn’t find right away the correct way to install it.
It’s beautiful now :sparkles::rainbow:
