### ISSUE TITLE
File top notification bar hard to read

### ISSUE THREAD

**Issue by camsteffen** [Vincent-P/gruvbox-intellij-theme#24]
See the yellow bar at the top of the file.
Version: 0.3.0

<img width="820" alt="image" src="https://user-images.githubusercontent.com/5565418/80000626-fc326f00-8482-11ea-9b7a-5b372e31491e.png">

**Comment by Vincent-P** [comment]
I can't reproduce it with master, can you test with master or latest update once it's out?

**Comment by camsteffen** [comment]
Looks good now!
