### ISSUE TITLE
Error description Text color same as the background color

### ISSUE THREAD

**Issue by big-lip-bob** [Vincent-P/gruvbox-intellij-theme#25]
![image](https://user-images.githubusercontent.com/41026257/80725254-1ca59d80-8b03-11ea-9d6f-66a4d318d234.png)
This should be straight forward enough, drove me crazy for a while

**Comment by big-lip-bob** [comment]
Using IntelliJ 2020.1 and the Rust Plugin, the descriptions of warns and errors just fade in the background by having the same colors

**Comment by Vincent-P** [comment]
Which theme are you using? (UI Theme and color scheme)
Does this happen with only a combination of both or a specific theme always does this?

**Comment by big-lip-bob** [comment]
Just the GruvBox out of the box, set on Editor and Appearance without tweaked values, this is Rust and also same problem for CLion.
