### ISSUE TITLE
"Command Abbreviations" stop working

### ISSUE THREAD

**Issue by marcoavaccaro** [Vincent-P/gruvbox-intellij-theme#35]
Hello,

After the last update of the Gruvox Theme some "command abbreviations" stop working... Like ==, !=, >=, <=.

**Comment by Vincent-P** [comment]
I'm not sure how it is related with gruvbox, can you explain what's wrong?
Have you tried another theme?

**Comment by marcoavaccaro** [comment]
> I'm not sure how it is related with gruvbox, can you explain what's wrong?
> Have you tried another theme?

I think I was not clearly enough. The codes still working, it's only a visual problem. Before the update when you digite "!=", the grovox theme wrote "≠". That "abbreviations" stopped working.

**Comment by Vincent-P** [comment]
You need to check "Enable font ligatures" in Settings -> Editor -> Font.

**Comment by marcoavaccaro** [comment]
"workbench.colorTheme": "Earthsong (rainglow)",
    "code-runner.runInTerminal": true,
    "editor.fontLigatures": null
}

I do not have a check box for this option. I need to change the "editor.fontLigatures" to **true**?

**Comment by Vincent-P** [comment]
Yes, which editor do you use?
This repository is the gruvbox theme of the Jetbrains IDE https://plugins.jetbrains.com/plugin/12310-gruvbox-theme.

**Comment by marcoavaccaro** [comment]
Oh, I really sorry. I'm using VS Code.

But Thank you for your support.
