### ISSUE TITLE
Light Theme uses wrong horizontal scroll colors

### ISSUE THREAD

**Issue by kles4enko** [Vincent-P/gruvbox-intellij-theme#36]
Example:
![image](https://user-images.githubusercontent.com/1761252/85292036-f9b0bd80-b4a3-11ea-9d23-059c6705185e.png)

Affected all light theme.

**Comment by Vincent-P** [comment]
I am not sure if it's possible to change the scrollbar's color.
Does the scrollbar look different with other themes?

**Comment by kles4enko** [comment]
Hello @Vincent-P!
After detailed look I see that Dark them also has same issue. Please check left horizontal and right vertical scrolls - they are ok:
![image](https://user-images.githubusercontent.com/1761252/99666937-b8393400-2a7c-11eb-8f58-8d52705ebb1b.png)

For the example from another theme, here is [Gradianto](https://plugins.jetbrains.com/plugin/12334-gradianto):
![image](https://user-images.githubusercontent.com/1761252/99667058-e0c12e00-2a7c-11eb-8adb-29006ee0cb67.png)

**Comment by bric3** [comment]
I second that, in fact i reported a similar issue in gradianto

https://github.com/thvardhan/Gradianto/issues/21
This was likely fixed on October 13 2020 (https://github.com/thvardhan/Gradianto/commits/master)
