### ISSUE TITLE
Declaration usage menu is hard to read in dark-hard theme

### ISSUE THREAD

**Issue by satyapramodh** [Vincent-P/gruvbox-intellij-theme#37]
when i open a method's declaration and usages menu (screenshots attached), some of the texts are hard to read.
1. fig 1: the shortcut is not readable until you hover over the menu item
2. fig 2: the header of declarations and usage menu/box is hard to read

![Screen Shot 2020-07-10 at 11 45 59 AM](https://user-images.githubusercontent.com/3414042/87188001-ee7ecf80-c2a2-11ea-8ff7-87a7bf46c241.png)
![Screen Shot 2020-07-10 at 11 45 10 AM](https://user-images.githubusercontent.com/3414042/87187925-d14a0100-c2a2-11ea-9be8-0b603d1d0c7e.png)

PyCharm 2020.1.3 (Professional Edition)
Build #PY-201.8538.36, built on July 7, 2020
Runtime version: 11.0.7+10-b765.64 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5

I would like to contribute. i see the xml for dark-hard but i need help setting up (java newbie). If u can help me fig out java version to use, java ide (eclipse?), compile process... i can help. If you have any quick material/links you can share i will go through it or i will take some time to learn through jetbrains docs and update.

Thank you for this amazing theme!

**Comment by Vincent-P** [comment]
Hello,
How do you open that menu, is it something specific to PyCharm?

**Comment by satyapramodh** [comment]
Yes i use pycharm. but i the right click menu with declaration or uses must be available in java and other ides of jetbrains as well. right?

**Comment by Vincent-P** [comment]
Closed because I can't reproduce and i don't know if the issue still exists.
The only clue I got is that sometimes if you change the color scheme without restarting some colors gets weird.
Feel free to reopen the issue if this problem still exists.
