### ISSUE TITLE
support for rider 2020.3 EAP 1?

### ISSUE THREAD

**Issue by djeikyb** [Vincent-P/gruvbox-intellij-theme#42]
I'm trying out the latest Rider EAP, does this plugin need another version bump? Like in: https://github.com/Vincent-P/gruvbox-intellij-theme/issues/31

I'm running rider version:

> JetBrains Rider 2020.3 EAP 1
> Build #RD-203.3645.15, built on September 23, 2020

**Comment by djeikyb** [comment]
I tried downloading the plugin zip and directly edited:

    gruvbox-theme/lib/gruvbox-theme-0.4.2.jar::META-INF/plugin.xml

to change the until-build attribute from:

    <idea-version since-build="183.0" until-build="202.*"/>

to:

    <idea-version since-build="183.0" until-build="203.*"/>

This let me manually install the plugin. So far so good?

**Comment by hravnx** [comment]
I have just created a PR #44 that fixes this.
