### ISSUE TITLE
Font ligatures are disabled

### ISSUE THREAD

**Issue by OwenTrokeBillard** [Vincent-P/gruvbox-intellij-theme#45]
[Font ligatures](https://www.jetbrains.com/webstorm/guide/tips/font-ligatures/) are disabled in the latest release (0.4.3). It's not mentioned in the [change notes](https://github.com/Vincent-P/gruvbox-intellij-theme/blob/fb112f35b00c9ee8d52b42e6d49c9064ce10017b/build.gradle#L30-L36). Looks like they were removed in [1ad4163](https://github.com/Vincent-P/gruvbox-intellij-theme/commit/1ad416308a62826c95f615c373841422e334dcc0#diff-ba601bb4e83dda84356fc61ebda01d300035416672512d3e79015ce6024ec414L1021). They were quite nice — any reason for this change?

#### 0.4.3
![image](https://user-images.githubusercontent.com/20851553/99756226-e84afc00-2aa9-11eb-9443-069ac951218d.png)

#### 0.4.2
![image](https://user-images.githubusercontent.com/20851553/99756416-57285500-2aaa-11eb-9be0-d30edd3cd0c7.png)

**Comment by dinhquochan** [comment]
Hi,

This is removed all default font options, you can enabled your own on **Preferences** > **Editor** > **Font**

![image](https://user-images.githubusercontent.com/9979458/103156962-f1359880-47e0-11eb-8d3b-dc4515a1b5e1.png)

**Comment by OwenTrokeBillard** [comment]
Thank you @dinhquochan.
