### ISSUE TITLE
Terminal links are not readable (in gruvbox dark)

### ISSUE THREAD

**Issue by bric3** [Vincent-P/gruvbox-intellij-theme#46]
I think links color could be tuned to be readable in dark gruvbox, all variant suffer the same issue.

![gruvbox dark soft](https://user-images.githubusercontent.com/803621/104508003-df793100-55e7-11eb-9498-e576cb5ca2b0.png)
![gruvbox dark medium](https://user-images.githubusercontent.com/803621/104508178-249d6300-55e8-11eb-907d-bc5036b3a5eb.png)
![gruvbox dark hard](https://user-images.githubusercontent.com/803621/104508081-00da1d00-55e8-11eb-9480-483001e7c637.png)

However I don;t really know where this settings exists, it doesn't seem to be user configurable in the console color scheme

**Comment by Vincent-P** [comment]
Thanks for you report, I will look into it for the next update.

**Comment by Vincent-P** [comment]
Unfortunately I can't reproduce this issue, I have the gruvbox light blue instead.

**Comment by bric3** [comment]
Indeed I cannot reproduce it anymore on 2020.1, Thanks for looking into it !
