### ISSUE TITLE
Use a more distinguishable colour for errors

### ISSUE THREAD

**Issue by velitasali** [Vincent-P/gruvbox-intellij-theme#48]
Hello,

First of all, thank you for this awesome theme. I am using it on all the JetBrains IDEs and I want to make a suggestion. 

> Kotlin, Unmodified Dark Medium Theme & Colour Scheme
> ![Screenshot from 2021-02-21 20-10-01](https://user-images.githubusercontent.com/10258162/108632583-cf732d80-7480-11eb-82e0-1e4f49266f6f.png)

* In the first two lines, the method `enableNetwork` is deprecated so the IDE is giving a warning.

* In the last two lines, the method `enableNetworkk` does not exist and the return value `truee` is misspelt.

I am aware that the deprecation is styled with italic text and keywords aren't underlined in normal circumstances, however, because, most of the time what helps me distinguish errors is the colour, I think it would be great if the error colour was different so it could be more distinguishable. Or the red colour reserved for errors only.

Thanks,
Keep up the good work :)

**Comment by Vincent-P** [comment]
It is an interesting problem and I am not sure how it is handled in other IDEs.
If anyone has suggestions on how it should look feel free to try and post here.

Keywords are red in the original gruvbox vim theme so maybe errors need another color?

**Comment by velitasali** [comment]
Not sure what would be the right choice, however, I think a different colour could be enough.

In this instance, I used `#B8BB26` which is part of the colour scheme:

![Screenshot from 2021-05-13 15-03-53](https://user-images.githubusercontent.com/10258162/118123322-c0a37380-b3fc-11eb-9f9a-777f63d7e3ee.png)

**Comment by Vincent-P** [comment]
So with #49, function and method calls have no special foreground anymore.
I also changed errors and deprecation warnings to only have a red underwave so now the red foreground is exclusively for keywords.
