### ISSUE TITLE
Different colors for string literals and method calls

### ISSUE THREAD

**Issue by zsolt-donca** [Vincent-P/gruvbox-intellij-theme#49]
First of all, I'd like to say that this theme is looking great! Keep up the good work!

My issue is that after using for a couple of days, I noticed that the fact that the string literals and method calls have the same greenish color can hinder readability, especially when string literals are passed as arguments to method calls. 

Take a look at the below example, and notice that the method calls `addAttribute` and `getValue` have the same color as their  string literal arguments:

![image](https://user-images.githubusercontent.com/6824167/110474091-ef912680-80e7-11eb-83dc-e1d72584d1da.png)

For comparison, this is how the same look like using the theme One Dark Vivid (notice that the colors are different):

![image](https://user-images.githubusercontent.com/6824167/110474321-34b55880-80e8-11eb-8d1b-12814d8bef0d.png)

Or when using the built-in theme Darcula:

![image](https://user-images.githubusercontent.com/6824167/110474434-531b5400-80e8-11eb-9193-c2b9c2d40eb0.png)

Or when using the built-in theme IntelliJ Light:

![image](https://user-images.githubusercontent.com/6824167/110474525-734b1300-80e8-11eb-80ef-9e048cb5ef90.png)

Notice that in all of the other examples, the method calls and the string literals are colored differently.

Also note that in the theme Gruvbox Material Dark in Visual Studio Code also uses different colors:

![image](https://user-images.githubusercontent.com/6824167/110474825-cf159c00-80e8-11eb-810f-f3887581a351.png)

@Vincent-P If you'd like, I can experiment with some colors and come back with a concrete proposal in the form of a pull request.

**Comment by Vincent-P** [comment]
Sorry for the late answer, feel free to experiment!
I'll gladly merge any PR you have.

**Comment by Vincent-P** [comment]
I personally really like how builtin themes handle this so I will try to do that in the next update.

**Comment by Vincent-P** [comment]
With https://github.com/Vincent-P/gruvbox-intellij-theme/commit/110d50128f565de2e653383cd1e5feeb2882bbfb functions and method calls have no special colors like built-in themes.
