### ISSUE TITLE
Unfocused tabs do not honor database color choice.

### ISSUE THREAD

**Issue by rholak** [Vincent-P/gruvbox-intellij-theme#5]
(PHPStorm 2019.1.3)

I have different colors set up for database connections, as well as the option to color tabs related to the connection. When I select a tab for a production database, for example, it shows my chosen color of red correctly. But when I choose another editor tab, the database tab reverts to the default Gruvbox unselected color.

Unselected:
![image](https://user-images.githubusercontent.com/423088/60024507-77f23e00-965d-11e9-9d7f-dd868bc03403.png)
Selected:
![image](https://user-images.githubusercontent.com/423088/60024543-8b050e00-965d-11e9-9261-4cfca3d48885.png)

**Comment by Vincent-P** [comment]
Thanks for you report!
Im going to take a look at this this week :)

**Comment by Vincent-P** [comment]
Is there a way to color an editor tab without using the database feature?

**Comment by rholak** [comment]
> Is there a way to color an editor tab without using the database feature?

I'm not sure about that, but I did figure out how to allow the database coloring to work.  
The EditorTabs.inactiveMaskColor is currently set to "#282828" in the theme.
By adding an alpha channel, I was able to get a result I liked using "#28282866" that allowed part of the database color to show.
As this is your theme, I will let you decide if you like this and/or want to change the alpha amount. Here is an example, using the color/alpha mask I tried:

![image](https://user-images.githubusercontent.com/423088/61228123-4106c980-a6eb-11e9-839d-2859f1a002b7.png)

The unselected database tab now has a masked/blended color using the red color I chose for the database.

**Comment by Vincent-P** [comment]
Okay I will set it to #28282866 then, tell me if it works in the next update!
