### ISSUE TITLE
Variables in debugger unreadable

### ISSUE THREAD

**Issue by eelcovv** [Vincent-P/gruvbox-intellij-theme#51]
Hi, first of all, I love this color scheme! But there is one issue which hold me from using this one as a default: the variables in de debugger are unreadable. I have added a screenshot

![image](https://user-images.githubusercontent.com/2842784/117143794-7d6c5380-adb1-11eb-9f09-384c7cdea425.png)
 
As you can see: the variable names are virtually the same color as the background. Any chance changing this ?

**Comment by Vincent-P** [comment]
Thanks for you report, I will look into it for the next update.

**Comment by Vincent-P** [comment]
Unfortunately I can't reproduce this issue when debugging Kotlin, variables names are fine:
![image](https://user-images.githubusercontent.com/10779205/119561827-f275ec00-bda5-11eb-8a57-aa93901c8aa2.png)

**Comment by eelcovv** [comment]
I see, I still have the same issue. In your case the keys are in the brownish color, and in my case they are still in yellow, so not visible. I am using Python, I an not sure if this matters. Is there a way to easily alter the color of one type of items (such as the keys in the debugger)?

**Comment by Vincent-P** [comment]
I still can't reproduce this with PyCharm, do you still have this problem?
![image](https://user-images.githubusercontent.com/10779205/140146322-488c2eb6-f0c6-4cbd-90f6-589769bf409e.png)

**Comment by eelcovv** [comment]
Just checked it again and now everything seems ok. Dont know what the root of the problem was, but it is looking fine now. thanks for this theme. I still love it!

**Comment by Vincent-P** [comment]
From my testing today it seems that some colors get weird if you change themes without restarting the editor.
