### ISSUE TITLE
DataGrip Incompatible

### ISSUE THREAD

**Issue by ghost** [Vincent-P/gruvbox-intellij-theme#54]
After updating DataGrip, Gruvbox Theme plugin is incompatible.

Gruvbox Theme plugin error:  required IDE build 211.* or older

DataGrip 2021.2
Build #DB-212.4746.86, built on July 26, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins: bundled-datagrip-help (212.4746.86)

**Comment by Vincent-P** [comment]
See #53
