### ISSUE TITLE
The plugin is incompatible with the latest Intellij Idea version.

### ISSUE THREAD

**Issue by jaideeprana** [Vincent-P/gruvbox-intellij-theme#56]
I have upgraded to the latest Intellij IDEA version which is 2021.2 and the Gruvbox plugin stopped working.

I am on MacOS big sur.

<img width="402" alt="Screenshot 2021-07-29 at 6 02 46 PM" src="https://user-images.githubusercontent.com/3875065/127492277-c7c48727-7c9f-4dfd-a0a0-a2c914b79323.png">

**Comment by Vincent-P** [comment]
Duplicate #53.
