### ISSUE TITLE
Change red color for something else

### ISSUE THREAD

**Issue by e-belair** [Vincent-P/gruvbox-intellij-theme#57]
I really like this theme. The only problem is the red color for keywords that is mixed with real errors. 
I would change for orange like `#FB8A34`
What do you think?

**Comment by Vincent-P** [comment]
Most gruvbox themes use red for keyword so I prefer to keep using red for them.

**Comment by Zackhardtoname** [comment]
If there any chance we could have an option in the plugin for users to change at least this specific color?

**Comment by Zackhardtoname** [comment]
[The most popular (I believe) Gruvbox plugin](https://github.com/morhetz/gruvbox) for Vim uses orange. :)
