### ISSUE TITLE
Missing color on method call after version 0.4.4

### ISSUE THREAD

**Issue by Liyixin95** [Vincent-P/gruvbox-intellij-theme#58]
after version 0.4.4:

![after](https://user-images.githubusercontent.com/10390125/127733190-2e2c95d0-d22d-4cbd-98f2-8ebc215af136.png)

before version 0.4.4:
![before](https://user-images.githubusercontent.com/10390125/127733207-9f329706-13a2-4579-8f1c-1e4e45eb191b.png)

The color on dark mode is alright. This is a bug or a intended change?

**Comment by Vincent-P** [comment]
It is intended (See #49).
