### ISSUE TITLE
Hard Wrap Guide is the same color as editor background in Dark Soft

### ISSUE THREAD

**Issue by DrOverbuild** [Vincent-P/gruvbox-intellij-theme#59]
All five other variants of the theme have a Hard Wrap Guide that is visible, but in Gruvbox Dark Soft, it's only _barely_ noticeable on the line you're working on.

If this was intentional, you can close this issue and I will enjoy a personal modification but if not I'd be happy to submit a pull request.

![hardwrap](https://user-images.githubusercontent.com/3422979/128245459-32d58dcd-4baf-4331-afd3-e3068c719487.PNG)

**Comment by Vincent-P** [comment]
Thanks for your feedback, the wrap guide will have the same color as the indent guides in the next update.
