### ISSUE TITLE
Support 2019.2

### ISSUE THREAD

**Issue by lancelote** [Vincent-P/gruvbox-intellij-theme#6]
First of all, thank you for the great plugin 👍 

Unfortunately, 0.1.2 plugin is not compatible with 2019.2+ versions, I had to tweak `until-build` manually to be able to install it from disk. EAP builds are already available so it would be great to be able to install the plugin directly from the marketplace.

P.S. 2019.3 support is also welcomed as I usually stick to nightly PyCharm builds, but this is probably not typical usecase.

**Comment by Vincent-P** [comment]
Do you know how to add compatibility with newer version?

EDIT: I think I managed to add compatibility for the 2019.2 and 2019.3 versions, can you confirm that it work?

**Comment by lancelote** [comment]
Unfortunately, [it is still not compatible](https://plugins.jetbrains.com/plugin/12310-gruvbox-theme/versions), I believe you missed a wild card:

```
sinceBuild '191.*'
```

**Comment by raqib007** [comment]
Unable to install theme from marketplace with webstorm 2019.2 also tried manually but not working...compatibility issue.....

**Comment by Vincent-P** [comment]
It should finally work with the next update but I am not sure about the 2019.3 version.
