### ISSUE TITLE
VCS ignored files highlighting is too bright in 2019.2

### ISSUE THREAD

**Issue by lancelote** [Vincent-P/gruvbox-intellij-theme#7]
Consider 2019.1 ignored file highlighting:

<img width="360" alt="old" src="https://user-images.githubusercontent.com/2500320/60578600-27c85980-9d8a-11e9-9c65-bb8f100b1610.png">

vs 2019.2

<img width="275" alt="new" src="https://user-images.githubusercontent.com/2500320/60578602-2860f000-9d8a-11e9-8771-e9f28c8228c8.png">

The new version is too bright, the text is hardly readable.

**Comment by Vincent-P** [comment]
I am not sure why it is brighter in the 2019.2 version.

**Comment by MarcinWieczorek** [comment]
I confirm

**Comment by MarcinWieczorek** [comment]
![grubbox](https://user-images.githubusercontent.com/3466984/61780686-3fcc4f80-ae03-11e9-9f59-607e720ff519.png)
I think shift+shift and ctrl+click popups might be related to this, although I don't know how it used to look. I'm on `pycharm 2019.1.3`
