### ISSUE TITLE
Support for Android Studio 3.4.2

### ISSUE THREAD

**Issue by Odaym** [Vincent-P/gruvbox-intellij-theme#8]
Would have loved to try it but it will not work with my latest version of Android Studio.

```
Android Studio 3.4.2
Build #AI-183.6156.11.34.5692245, built on June 27, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
```
![00557E99-55D1-4B0A-8170-F23FA0642A3B](https://user-images.githubusercontent.com/753054/62367481-75bfb100-b532-11e9-94f1-7f1bf06d4bf5.jpg)

**Comment by Vincent-P** [comment]
Thanks for your report!
I don't know how you manage to go that far, when I tried on Windows I got a compatibility error message.
A new version will be available soon.
