### ISSUE TITLE
flickrs in Qtile

### ISSUE THREAD

**Issue by zordsdavini** [Vincent-P/gruvbox-intellij-theme#9]
Installed in phpStorm (additionally used as DB client). In query window during scroll gets flickrs.

Archlinux, Qtile
![2019-08-14-120927_3840x1200_scrot](https://user-images.githubusercontent.com/4191548/63009536-6115de00-be8d-11e9-9c5a-a299b67c2358.png)

**Comment by Vincent-P** [comment]
Sorry for the late answer, can you add post a gif or small video showing your problem?
